spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: ${DB_MIGRATION_ENABLED:false}
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_NAME:postgres}
    user: ${DB_MIGRATION_USERNAME:postgres}
    password: ${DB_MIGRATION_PASSWORD:postgres}
    contexts: ${DB_MIGRATION_CONTEXTS:dev}

