spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_CONNECTION_POOL:5}
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: InternalDMCHikariCP

  liquibase:
    enabled: ${DB_MIGRATION_ENABLED:false}
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_NAME:postgres}
    user: ${DB_MIGRATION_USERNAME:postgres}
    password: ${DB_MIGRATION_PASSWORD:postgres}
    contexts: ${DB_MIGRATION_CONTEXTS:dev}

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: ${SWAGGER_ENABLED:true}
    disable-swagger-default-url: true

properties:
  product-service:
    base-url: ${PRODUCT_SERVICE_BASE_URL:}
