version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pract4-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  postgres_data:

